apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

namespace: prod-ranx

resources:
  - ../../base

secretGenerator:
  - name: ranx-env
    envs:
      - .env.prod
    type: Opaque

generatorOptions:
  disableNameSuffixHash: false
