apiVersion: v1
kind: Namespace
metadata:
  name: instol
  labels:
    name: instol
    component: application
    purpose: business-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instol-app
  namespace: instol
  labels:
    app: instol-app
    component: application
spec:
  replicas: 1  # Autopilot manages scaling
  selector:
    matchLabels:
      app: instol-app
  template:
    metadata:
      labels:
        app: instol-app
    spec:
      containers:
        - name: instol-app
          image: us-central1-docker.pkg.dev/instol/n8n-saas/n8n-saas-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: instol-app-secrets  # Store sensitive env vars in a Secret
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            readOnlyRootFilesystem: true
      automountServiceAccountToken: true
      serviceAccountName: instol-app-sa
---
apiVersion: v1
kind: Service
metadata:
  name: instol-app
  namespace: instol
spec:
  selector:
    app: instol-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instol-app-sa
  namespace: instol
  annotations:
    iam.gke.io/gcp-service-account: "n8n-gke-manager@instol.iam.gserviceaccount.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: instol-app-secrets
  namespace: instol
type: Opaque
data:
  API_BASE_URL: aHR0cHM6Ly9zdGFnZS5pbnN0b2wuY2xvdWQ=
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfR2tSbndVN3V4WjFPQGVwLXN0aWxsLXVuaW9uLWFoMWNscjlnLXBvb2xlci5jLTMudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZSZjaGFubmVsX2JpbmRpbmc9cmVxdWlyZQ==
  GOOGLE_CLIENT_ID: BASE64_GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: BASE64_GOOGLE_CLIENT_SECRET
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
  CLOUDFLARE_API_TOKEN: WkdlYWI2bHVybmZTbFhRZVpVQmExa0RQbHp1VlV4b0RxNEsxRmFqSQ==
  CLOUDFLARE_TUNNEL_TOKEN: ZXlKaElqT2lNR1kyWVRFMk5qVTVNVEV3TURnME1qVmFOSGd3TURBd01qQXhOalF3TURSaUxYVXdNbVl0WkRRM1pUQXhPREJpTjJSbCJ9
  CLOUDFLARE_TUNNEL_ID: YTg0ODY4OTktY2MxMi00NDY2LWEwMzMtNmYwMWE2YTllNmQ3
  CLOUDFLARE_ACCOUNT_ID: MGYyYTE2NjU1MWFhM2M1YWZhNjE5MzVlMTdhMTg4ZTUi
  CLOUDFLARE_ZONE_ID: ZTVlNGM2ZmNlOTA1MmNmODgyM2MyOTFjNTRkNjRiNTE=
  POLAR_ACCESS_TOKEN: cG9sYXJfb2F0X0U2ZFljQlJLSGxYZkZRR2RYcW41QkNJbXp5VWJWTk45OTdjQTN5SjR3bw==
  POLAR_PRODUCT_ID: YTU1MGI1MjktY2UzZS00NWUxLTlkNjctMzQ0NTBlZTgyOTcw
  POLAR_WEBHOOK_SECRET: cG9sYXJfd2hzX0JBNXN3anBqUkN5V2xnZ3RmcHpGT01HdGptTWpUNERVVktoaTAyaGFPb2k=
  POLAR_SERVER: c2FuZGJveA==
  HOST: MC4wLjAuMA==
