apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ranx-namespace-admin
rules:
  # Namespace lifecycle
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # Workloads
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # Services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # Pods (mostly indirect, but needed)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]

  # PVC
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # ConfigMaps (safe)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ranx-namespace-admin-binding
subjects:
  - kind: ServiceAccount
    name: prod-ranx-app-sa
    namespace: prod-ranx
  - kind: ServiceAccount
    name: stage-ranx-app-sa
    namespace: stage-ranx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ranx-namespace-admin
