apiVersion: v1
kind: Namespace
metadata:
  name: ranx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranx-app
  labels:
    app: ranx-app
    component: application
spec:
  replicas: 1  # Autopilot manages scaling
  selector:
    matchLabels:
      app: ranx-app
  template:
    metadata:
      labels:
        app: ranx-app
    spec:
      containers:
        - name: ranx-app
          image: us-central1-docker.pkg.dev/instol/n8n-saas/n8n-saas-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ranx-env
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            readOnlyRootFilesystem: true
      automountServiceAccountToken: true
      serviceAccountName: ranx-app-sa
---
apiVersion: v1
kind: Service
metadata:
  name: ranx-app
spec:
  selector:
    app: ranx-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ranx-app-sa
  annotations:
    iam.gke.io/gcp-service-account: "n8n-gke-manager@instol.iam.gserviceaccount.com"
