apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stage-

namespace: stage-ranx

resources:
  - ../../base

secretGenerator:
  - name: ranx-env
    envs:
      - .env.stage
    type: Opaque

generatorOptions:
  disableNameSuffixHash: false
