apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: instol-stage

resources:
  - ../../base

secretGenerator:
  - name: instol-env
    envs:
      - .env.stage
    type: Opaque

generatorOptions:
  disableNameSuffixHash: false
